include: package:very_good_analysis/analysis_options.yaml

formatter:
  page_width: 100

linter:
  rules:
    lines_longer_than_80_chars: false
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    avoid_catches_without_on_clauses: false
